name: Notify Telegram on Release

on:
  release:
    types: [created, published]
  workflow_dispatch:    # trigger manuale per test

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Telegram with button
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{
            \"chat_id\": \"(quichatid)\",
            \"parse_mode\": \"Markdown\",
            \"text\": \"ðŸ”¥ *Aggiornamento Disponibile!* ðŸ”¥\n-Nuova Release per *NFC Fucker*-\n*Versione:* ${{ github.event.release.name }}\nControlla il Changelog per le novitÃ !\",
            \"reply_markup\": {
              \"inline_keyboard\": [[
                {\"text\": \"ðŸ”— Vai al sito\", \"url\": \"https://macolab.github.io/ESP32C3-NFC-FUCKER/\"}
              ]]
            }
          }"
